"""empty message

Revision ID: 1542b0462ef4
Revises: fc9b2df95478
Create Date: 2023-01-31 14:07:42.549962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1542b0462ef4'
down_revision = 'fc9b2df95478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_pwd', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_locked')
        batch_op.drop_column('failed_pwd')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###
